---
title: "Aging"
output: html_document
date: "2025-01-28"
---
Librerias
```{r setup, include=TRUE}

library(data.table)
library(dplyr)
library(knitr)
library(kableExtra)
library(biomaRt)
library(ggplot2)
library(ggpubr)
library(pheatmap)
library(ggfortify)
library(edgeR)
library(limma)

```

Lectura de los datos
```{r}

datos <- fread("GSE262290_brain_RNA_gene_counts.tsv", sep = "\t", header = TRUE)

knitr::opts_chunk$set(echo = TRUE)
```

Graficas de correlaciones positivas
```{r}

edades <- as.numeric(gsub("([0-9]+)M.*", "\\1", colnames(datos)[2:ncol(datos)]))

datos_transpuestos <- data.frame(t(datos[, 2:ncol(datos)]))

rownames(datos_transpuestos) <- colnames(datos)[2:ncol(datos)] # Usar nombres de columnas originales

colnames(datos_transpuestos) <- datos$V1 
datos_transpuestos$edad <- edades

datos_transpuestos[, 1:(ncol(datos_transpuestos) - 1)] <- apply(datos_transpuestos[, 1:(ncol(datos_transpuestos) - 1)], 2, as.numeric)

datos_transpuestos[, 1:(ncol(datos_transpuestos) - 1)] <- apply(datos_transpuestos[, 1:(ncol(datos_transpuestos) - 1)], 2, as.numeric)

matriz_correlacion <- cor(datos_transpuestos[, 1:(ncol(datos_transpuestos) - 1)], datos_transpuestos$edad)

if (is.null(rownames(matriz_correlacion))) {
  rownames(matriz_correlacion) <- colnames(datos_transpuestos)[1:(ncol(datos_transpuestos)-1)]
}

correlaciones_ordenadas <- sort(abs(matriz_correlacion[, 1]), decreasing = TRUE) 
top_10_genes <- names(correlaciones_ordenadas[1:10])

for (gen in top_10_genes) {
  gen_index <- which(colnames(datos_transpuestos) == gen)

  if (length(gen_index) > 0) {
    correlation_value <- matriz_correlacion[gen, 1] 

    print(ggplot(datos_transpuestos, aes(x = edad, y = datos_transpuestos[, gen_index])) +
      geom_point() +
      geom_smooth(method = "lm") +
      labs(
        title = paste("Correlación entre la edad y la expresión del gen", gen, "\nCorrelación:", round(correlation_value, 3)), 
        x = "Edad (meses)",
        y = "Expresión génica"
      ) +
      theme_bw())
  } else {
    print(paste("No se encontró el índice para el gen:", gen))
  }
}

correlaciones_ordenadas <- sort(abs(matriz_correlacion[, 1]), decreasing = TRUE)
top_10_genes <- names(correlaciones_ordenadas[1:10])

tabla_resultados <- data.frame(
  ID_gen = top_10_genes,
  Correlacion = numeric(10),
  Valor_p = numeric(10)
)

for (gen in top_10_genes) {
  gen_index <- which(colnames(datos_transpuestos) == gen)

  if (length(gen_index) > 0) {
    correlation_value <- matriz_correlacion[gen, 1]

    print(
      ggplot(datos_transpuestos, aes(x = edad, y = datos_transpuestos[, gen_index])) +
        geom_point(
          color = "skyblue", # Color de los puntos
          size = 3, # Tamaño de los puntos
          alpha = 0.8 # Transparencia de los puntos
        ) +
        geom_smooth(
          method = "lm", # Método de la línea de tendencia
          color = "royalblue", # Color de la línea de tendencia
          linewidth = 1.2 # Grosor de la línea
        ) +
        labs(
          title = paste("Correlación entre la edad y la expresión del gen", gen, "\nCorrelación:", round(correlation_value, 3)),
          x = "Edad (meses)",
          y = "Expresión génica"
        ) +
        theme_bw() + # Tema en blanco y negro
        theme(
          plot.title = element_text( # Estética del título
            hjust = 0.5, # Centrar el título
            size = 16, # Tamaño del título
            face = "bold" # Negrita el título
          ),
          axis.title = element_text(size = 14), # Tamaño de los títulos de los ejes
          axis.text = element_text(size = 12) # Tamaño del texto de los ejes
        )
    )
  } else {
    print(paste("No se encontró el índice para el gen:", gen))
  }
}

```

Tabla de genes con correlación positiva y su valor de P
```{r}
print(tabla_resultados)
```

Graficas de correlaciones negativas
```{r}

correlaciones_negativas <- matriz_correlacion[, 1] 
correlaciones_ordenadas_neg <- sort(correlaciones_negativas, decreasing = FALSE)
top_10_genes_neg <- names(correlaciones_ordenadas_neg[1:10])

tabla_resultados_neg <- data.frame(
  ID_gen = top_10_genes_neg,
  Correlacion = numeric(10),
  Valor_p = numeric(10)
)

for (i in 1:10) {
  gen <- top_10_genes_neg[i]
  gen_index <- which(colnames(datos_transpuestos) == gen)

  if (length(gen_index) > 0) {
    correlation_result <- cor.test(datos_transpuestos$edad, datos_transpuestos[, gen_index])
    tabla_resultados_neg$Correlacion[i] <- correlation_result$estimate
    tabla_resultados_neg$Valor_p[i] <- correlation_result$p.value
  } else {
    print(paste("No se encontró el índice para el gen:", gen))
  }
}

for (gen in top_10_genes_neg) {
  gen_index <- which(colnames(datos_transpuestos) == gen)

  if (length(gen_index) > 0) {
    correlation_value <- matriz_correlacion[gen, 1]

    print(
      ggplot(datos_transpuestos, aes(x = edad, y = datos_transpuestos[, gen_index])) +
        geom_point(
          color = "#66C2A5", # Color de los puntos (verde azulado)
          size = 3, # Tamaño de los puntos
          alpha = 0.8 # Transparencia de los puntos
        ) +
        geom_smooth(
          method = "lm", # Método de la línea de tendencia
          color = "#FC8D62", # Color de la línea de tendencia (naranja)
          linewidth = 1.2 # Grosor de la línea
        ) +
        labs(
          title = paste("Correlación entre la edad y la expresión del gen", gen, "\nCorrelación:", round(correlation_value, 3)),
          x = "Edad (meses)",
          y = "Expresión génica"
        ) +
        theme_bw() + # Tema en blanco y negro
        theme(
          plot.title = element_text( # Estética del título
            hjust = 0.5, # Centrar el título
            size = 16, # Tamaño del título
            face = "bold" # Negrita el título
          ),
          axis.title = element_text(size = 14), # Tamaño de los títulos de los ejes
          axis.text = element_text(size = 12) # Tamaño del texto de los ejes
        )
    )
  } else {
    print(paste("No se encontró el índice para el gen:", gen))
  }
}



```

Tabla de genes con correlación negativa y su valor de P
```{r}
print(tabla_resultados_neg)
```

ANOVA
```{r}

correlaciones_positivas <- matriz_correlacion[, 1]
correlaciones_ordenadas_pos <- sort(correlaciones_positivas, decreasing = TRUE)
top_5_genes_pos <- names(correlaciones_ordenadas_pos[1:5])

correlaciones_negativas <- matriz_correlacion[, 1]
correlaciones_ordenadas_neg <- sort(correlaciones_negativas, decreasing = FALSE)
top_5_genes_neg <- names(correlaciones_ordenadas_neg[1:5])

top_10_genes <- c(top_5_genes_pos, top_5_genes_neg)

tabla_resultados <- data.frame(
  ID_gen = top_10_genes,
  Correlacion = numeric(10),
  Valor_p = numeric(10)
)

for (i in 1:10) {
  gen <- top_10_genes[i]
  gen_index <- which(colnames(datos_transpuestos) == gen)

  if (length(gen_index) > 0) {
    correlation_result <- cor.test(datos_transpuestos$edad, datos_transpuestos[, gen_index])
    tabla_resultados$Correlacion[i] <- correlation_result$estimate
    tabla_resultados$Valor_p[i] <- correlation_result$p.value
  } else {
    print(paste("No se encontró el índice para el gen:", gen))
  }
}

print(tabla_resultados)

nombres_genes_limpios <- make.names(colnames(datos_transpuestos)[1:(ncol(datos_transpuestos) - 1)])

colnames(datos_transpuestos)[1:(ncol(datos_transpuestos) - 1)] <- nombres_genes_limpios

datos_transpuestos <- datos_transpuestos %>%
  mutate(etapa_vida = case_when(
    edad >= 2 & edad <= 6 ~ "Joven",
    edad > 6 & edad <= 18 ~ "Adulto",
    edad > 18 & edad <= 30 ~ "Viejo"
  ))

for (gen in top_10_genes) {
  gen_index <- which(colnames(datos_transpuestos) == gen)

  if (length(gen_index) > 0) {
    print(
      ggplot(datos_transpuestos, aes(x = etapa_vida, y = datos_transpuestos[, gen_index])) +
        geom_boxplot(
          aes(fill = etapa_vida), 
          color = "black",
          outlier.color = "red", 
          outlier.shape = 19,
          outlier.size = 2 
        ) +
        scale_fill_manual(values = c("#66C2A5", "#FC8D62", "#8DA0CB")) +
        labs(
          title = paste("Expresión del gen", gen, "por etapa de vida"),
          x = "Etapa de vida",
          y = "Expresión génica"
        ) +
        theme_bw() + 
        theme(
          plot.title = element_text( 
            hjust = 0.5, 
            size = 16, 
            face = "bold" 
          ),
          axis.title = element_text(size = 14), 
          axis.text = element_text(size = 12),
          legend.position = "none"
        )
    )
  }
}

```

PCA
```{r}

edades <- as.numeric(gsub("([0-9]+)M.*", "\\1", colnames(datos)[2:ncol(datos)]))

datos_transpuestos <- data.frame(t(datos[, 2:ncol(datos)]))

rownames(datos_transpuestos) <- colnames(datos)[2:ncol(datos)] 

colnames(datos_transpuestos) <- datos$V1 
datos_transpuestos$edad <- edades

datos_transpuestos$etapa_vida <- ifelse(datos_transpuestos$edad < 6, "Joven", "Adulto")

datos_transpuestos[, 1:(ncol(datos_transpuestos) - 1)] <- apply(datos_transpuestos[, 1:(ncol(datos_transpuestos) - 1)], 2, as.numeric)

datos_pca_preparado <- datos_transpuestos[, -ncol(datos_transpuestos)]

datos_pca <- t(datos_pca_preparado[, -ncol(datos_pca_preparado)])

reg.pca <- prcomp(datos_pca, center = TRUE, scale = FALSE)

pca_coords <- as.data.frame(reg.pca$x)

pca_coords$etapa_vida <- datos_transpuestos$etapa_vida[match(rownames(pca_coords), rownames(datos_transpuestos))]

p <- ggplot(pca_coords, aes(x = PC1, y = PC2, color = etapa_vida)) +
  geom_point(
    size = 4, 
    alpha = 0.8, 
    shape = 19 
  ) +
  scale_color_manual(values = c("#66C2A5", "#FC8D62")) + 
  labs(
    title = "PCA de expresión génica",
    x = paste0("PC1 (", round(reg.pca$sdev[1]^2 / sum(reg.pca$sdev^2) * 100, 1), "%)"), 
    y = paste0("PC2 (", round(reg.pca$sdev[2]^2 / sum(reg.pca$sdev^2) * 100, 1), "%)"), 
    color = "Etapa de vida"
  ) +
  theme_bw() + 
  theme(
    plot.title = element_text( 
      hjust = 0.5, 
      size = 18,
      face = "bold" 
    ),
    axis.title = element_text(size = 16), 
    axis.text = element_text(size = 14), 
    legend.title = element_text(size = 14), 
    legend.text = element_text(size = 12) 
  )

print(p)

PC1.genes <- data.frame(sort((reg.pca$rotation[, "PC1"]), decreasing = TRUE))
PC2.genes <- data.frame(sort((reg.pca$rotation[, "PC2"]), decreasing = TRUE))

print(head(PC1.genes, 100))

print(head(PC2.genes, 100))
```
